# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: false
# Issues with these labels will never be considered stale
exemptLabels:
  - ðŸ„ð“”ðŸ‘¢ðŸ‘¢ â“‚ð“”
  - ðŸ‘‘ Winner!
# Label to use when marking an issue as stale
staleLabel: Stale crap ðŸ’©
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Why did the stale issue felt like it was stuck in a rut ? Cause it hadn't been resolved for so long....
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
